### ISSUE TITLE
Written outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#12] opened 2018-10-15 21:38 UTC

**Comment by rrrutledge** [comment] 2018-11-07 23:45
@ttyler01 interested in taking a crack (backed up by @mrsanz)

**Comment by maxcapraro** [comment] 2019-01-10 14:09
I renamed this to `video outline` to avoid confusion (initially thought it is a duplicate of #27 ). Please feel free to rename if I misunderstood something.

**Comment by maxcapraro** [comment] 2019-01-10 14:12
Renamed it back as #10 appears to be the video outline for "trusted commiter". Sorry.

**Comment by rrrutledge** [comment] 2019-01-10 14:14
The idea was to produce an outline of the written content for quick review before taking the time for a  full-blown article.  Which I think we did at some point.

**Comment by lenucksi** [comment] 2019-03-17 13:25
It's in done, thus can be closed.

**Closed by lenucksi** 2019-03-17 13:25 UTC
Labels: Trusted Committer
