### ISSUE TITLE
Chinese translation of "Product Owner" section

### ISSUE THREAD

**Issue by WillemJiang** [InnerSourceCommons/InnerSourceLearningPath#321] opened 2020-10-03 02:37 UTC
It's time to finish the translation  of Product Owner.

**Comment by lenucksi** [comment] 2020-10-03 10:05
Hi @WillemJiang! Thanks for raising this and bringing up the pull request with the translation! :+1: :tada:

**Comment by rrrutledge** [comment] 2020-10-03 22:32
This is good - the problem is that we don’t really have an English article in the first place so there’s nothing to translate.  All we have checked in is the transcript but no one has really taken the time to make an article out of that.

**Comment by WillemJiang** [comment] 2020-10-04 02:31
I noticed this section is based on the transcript of the video.  From my understanding,  production owner is more like a manager role, it's hard for programer to write an article about it.

**Comment by rrrutledge** [comment] 2020-10-05 18:40
Just skip it for now, @WillemJiang.  We don't even publish these in English.

**Closed** 2020-10-22 15:43 UTC
Labels: Article, Product Owner, Translations
