### ISSUE TITLE
fix the slack inviter

### ISSUE THREAD

**Issue by nohorse** [InnerSourceCommons/InnerSourceLearningPath#97] opened 2019-07-16 23:28 UTC
following the "join the slack" call to action at OSCON

https://isc-inviter.herokuapp.com/ is what's linked to on the docs (somewhere) and when I try login in it gives an error about not being a paid version.

![image](https://user-images.githubusercontent.com/311063/61336590-be633480-a7e6-11e9-83d2-3e66b0dcd425.png)

**Comment by rrrutledge** [comment] 2019-07-22 23:58
Thanks for reporting this, Mark.  We'll take a look, and in the meantime please use this link to join: https://join.slack.com/t/innersourcecommons/shared_invite/enQtNjk5MzE5Njc4NTE3LWZiNjY4NjFkOThlYmJiYjBjZDE4OWYyNTFmZGU1ZGVkNzU4MThjNTk1MGUzMmQ3OTgxYWRjNjU5MWM1N2VjMzE.

**Comment by rrrutledge** [comment] 2019-08-05 21:36
Duplicate of https://github.com/InnerSourceCommons/infrastructure/issues/8.  Link on the main page should be working now.  Can you confirm, @nohorse?

**Closed by rrrutledge** 2019-08-05 21:36 UTC
Labels: Meta
