### ISSUE TITLE
Plan for IBM Watson powered translations to the learning path.

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#468] opened 2022-03-31 17:56 UTC
Folks at IBM are willing to contribute internal resources (Watson translator) for ISC content.  We should figure out what is available and come up with a plan for what we are going to do to leverage those resources toward the learning path.

The plan should be encapsulated in a set of cards here on the board that we can review together.

**Comment by tsadler1988** [comment] 2022-04-11 16:09
For now we will be using this manually. In the future we may want to explore automation if IBM are able to expose an endpoint.

**Comment by tsadler1988** [comment] 2022-06-21 16:01
Duplicate of #472

**Closed by tsadler1988** 2022-06-21 16:01 UTC
